### PR TITLE
feat: add angular 10 compat

### PR DESCRIPTION
**Pull request by sguiheux**

### CODE REVIEW

**Comment by etvoorde** [comment]
Considering that the last commit was Jul 8, 2019 I am concerned that @Stabzs may not have time to process this pull request. Would there by any other option to make this available?

**Comment by Stabzs** [comment]
I apologize everyone, I have been completely tied up until now but I will look at the package upgrade this week. Thank you for the PR!

**Comment by Stabzs** [comment]
I'm looking at a full update to Angular 10 due to deprecated dependencies.  This is taking just a bit longer than expected but I'll have an updated version out soon.

**Comment by Stabzs** [comment]
The library has been republished under version 10.0.0.  Due to the amount of source that needed to change by switching to angular-cli, the PR was no longer valid so I'm closing this.  Thank you for the effort to get the change made!

**Pull request closed without merging**
