### PR TITLE
Fix Angular CLI build with index signatures

### PR DESCRIPTION
**Pull request by andrewpmontgomery**
Fix for bug #148

### CODE REVIEW

**Comment by Stabzs** [comment]
Thanks for bringing this up and interesting solution.  Thank you for your work on it.  

One issue now is that if a user wanted to extend toast types, they wouldn't be able to since the strongly-typed model cannot be expanded. I need to take a closer look at the issue before merging in this PR.

**Comment by andrewpmontgomery** [comment]
I've left the `ToastType` open with `| string` at the end, so that users can still extend it. This means we get intellisense in editors (tested in WebStorm and in Visual Studio Code), but users can keep using their custom toast types.

Alternatively, we could implement a simpler fix for the bug, by just changing toaster-config.ts like this:
```
export interface IToasterConfig {
  ...
  typeClasses?: { [key: string]: string }
  iconClasses?: { [key: string]: string }
  ...
}
export declare class ToasterConfig implements IToasterConfig {
  ...
  typeClasses: { [key: string]: string }
  iconClasses: { [key: string]: string }
  ...
}
```

**Comment by Stabzs** [comment]
@andrewpmontgomery I missed the string union...I think this approach makes a lot of sense and builds a stronger API.  Thanks again for getting this done.

**Comment by Stabzs** [comment]
@andrewpmontgomery I'm reverting this PR.  This does not compile without errors, see https://travis-ci.org/Stabzs/Angular2-Toaster/builds/350897976

If you implement the simpler fix (which should satisfy the errors), I'll merge that in instead.

**Pull request merged**
