### PR TITLE
feat(scss): Add toaster.scss and node-sass compilator

### PR DESCRIPTION
**Pull request by bastienmoulia**
I add a toaster.scss with node-sass to generate the CSS file (no change on that).

I put some variables in it (colors, icons, breakpoints) which are the main ones modified for me. But others can be added too.

### CODE REVIEW

**Comment by bastienmoulia** [comment]
@Stabzs Due to the order in the SCSS map, the class `icon-*` are not in the same order, but the images should be good.

I can make a PR in the branch 5.x.x this evening.

**Comment by Stabzs** [comment]
@bastienmoulia thanks for changing the target branch and sorry for the delayed response.  Can you please resolve the conflicts against the new 5.x.x branch so that I can merge in?  I reviewed your feedback on the SCSS mapping and I agree, that looks good!

**Comment by bastienmoulia** [comment]
I generate the *package-lock.json* from scratch because there was to many diff.

**Comment by Stabzs** [comment]
@bastienmoulia thanks again!  I'll retest these changes and bump another package version.

**Pull request merged**
