### PR TITLE
Upgrade to Angular 2.0.0 RC5 + encapsulte into NgModule

### PR DESCRIPTION
**Pull request by bernhard-niedermayer**
solves #47

### CODE REVIEW

**Comment by laco0416** [comment]
please move `@angular/*` dependencies into `peerDependencies` because I want to use this package with nightly-builds packages like `angular/core-builds`.

**Comment by Stabzs** [comment]
Thank you so much for all of your hard work on this!  It was a ton of cleanup in the demo projects and much-needed optimizations and it is greatly appreciated!

A few fixes please, before this can be merged.

`exports.TostModule` in angular2-toaster-js is a typo and should be updated to `exports.ToastModule` please.

The test coverage dropped because you modified the callback on line 712.  This incorrectly causes that path to no longer get tested.  Please adjust test to return coverage back to 100%.

Once these two modifications are made, I'll be more than happy to merge this in.

**Comment by Stabzs** [comment]
@laco0416  I'm having difficulty justifying moving the angular2 dependencies to peerDependencies just to support nightly builds.  This will certainly cause a lot of confusion for a number of users when their installs proceed with just a warning but the version isn't present for a build.  

Moving it to devDependency is flat out incorrect and a poor representation of the dependencies for the library.

**Comment by laco0416** [comment]
@Stabzs does "users" mean contributors? almost *users* install explicitly angular2 and then install plugins. usually, `peerDependencies` doesn't cause confusion.

if some users (including me) want to use nightly-builds, some warning messages will appear. it's no problem because they want to go off the standard way.

**Comment by bernhard-niedermayer** [comment]
I have just added 2 commits. 
The first one to fix the typo in angular2-toaster-js,
the second one to fix the test.

**Comment by Stabzs** [comment]
@laco0416  I meant in the context of consumers of the library.

However, you make a great point...this library is a plugin and peer dependencies fit plugins better since that way they can be dropped in more easily.  I'll update the dependency type.

**Comment by Stabzs** [comment]
@bernhard-niedermayer thank you for making the changes and thank you for your hard work on this!

**Comment by Stabzs** [comment]
A new npm release will be created after README documentation is updated to match NgModule-style inclusions.

**Pull request merged**
